#!/usr/bin/env python3
"""The cast: which file each character's animations come from, and how big
each one is drawn.

[`10-second-b3d-family.md`](../docs/10-second-b3d-family.md) read
`PerfectMovers.B3D` and found the seven per-animation columns -- width,
height, ground offset among them -- and noted that the animation *names* in
the file are read into stack scratch and thrown away.  That left the obvious
question open: if the shipping build reaches its animations by number, what
file does a number open?

`LoadCharacterAnims` at `0x009a54` answers it.  It loops over one character's
animation slots and formats a path per slot, and which path is a thirteen-arm
jump table on `character - 6`:

    0 - 5    $Characters/<Name>.<slot+1>.anim    and .mask
    6, 11, 14   $Perfect/<Name>/<Name>.Run.anim  -- slot 1 only, no stand
    7, 8, 9, 10, 13   the same, plus .stand.anim for slot 2
    12       $Perfect/Chameleon/chameleon.run.anim, .Stand.anim, no mask
    15       $Perfect/Loki/Raven.Run.anim         -- Raven lives in Loki's
    16, 17, 18   $Perfect/PerfectOne/{Male,Female,Robot}/p*.Run.anim

with the character's name taken from the table at `0x058640` and the loop
running slot 1 upwards -- slot 0, every character's death animation, is not
loaded here -- and stopping at slot 3 for anything past character 5.

Every one of the 67 names that rule generates is on the disc.  Three files in
`$Characters` are not generated by it and are not named anywhere else:
`Medusa.1.anim`, `Medusa.2.mask` and `Picasso.1.plut`.

Each animation loads **two** files.  The `.mask` has the same frame count and
the same pixel size as its `.anim`, at 4 bpp against 6, with a sixteen-entry
grey ramp for a palette, and drawn it is a thin outline of the body and its
parts.  `0x017998` copies the character CCB's `ccb_XPos`, `ccb_YPos`,
`ccb_HDX` and `ccb_VDY` into the mask's and draws the mask **first**.

    python tools/movers.py
    python tools/movers.py --verify
    python tools/movers.py --sheet out/cast.png

See docs/24.
"""
import os, sys, struct

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cel
from b3d2 import read_any

# `0x058640`, the character name table -- and the name is what the paths are
# built from, so the order matters here.  See docs/06.
NAMES = ['Goner', 'Picasso', 'Tork', 'Kilroy', 'Venus', 'David', 'Medusa',
         'Tesla', 'Balkan', 'Silva', 'Fly', 'Riberto', 'Chameleon', 'Chance',
         'Loki', 'Raven', 'PerfectMale', 'PerfectFemale', 'PerfectRobot']

# The three arms of `0x009b2c`'s jump table that differ only in which suffixes
# they use.  Everything else is a special case of its own.
RUN_ONLY = {6, 11, 14}                       # Medusa, Riberto, Loki
RUN_AND_STAND = {7, 8, 9, 10, 13}            # Tesla, Balkan, Silva, Fly, Chance

PLAYER_FORM = {16: ('Male', 'pmale'), 17: ('Female', 'pfemale'),
               18: ('Robot', 'probot')}

RUN_SLOT, STAND_SLOT = 1, 2


def slot_files(char, slot):
    """`(anim, mask)` for one character's animation slot, relative to
    `Perfect/`, or `(None, None)` where the loader stores a null pointer.

    Transcribed from `0x009a54`.  The case of these names is the code's, not
    the disc's: it asks for `Tesla/Tesla.stand.anim` and the disc holds
    `Tesla/tesla.stand.anim`, so the File folio's lookup folds case.
    """
    n = NAMES[char]
    if char <= 5:                                    # `0x00a02c`
        return ('Characters/%s.%d.anim' % (n, slot + 1),
                'Characters/%s.%d.mask' % (n, slot + 1))
    if char in RUN_ONLY:                             # `0x009c74`
        if slot != RUN_SLOT:
            return (None, None)
        return ('%s/%s.Run.anim' % (n, n), '%s/%s.Run.mask' % (n, n))
    if char in RUN_AND_STAND:                        # `0x009cc4`
        s = 'Run' if slot == RUN_SLOT else 'stand'
        return ('%s/%s.%s.anim' % (n, n, s), '%s/%s.%s.mask' % (n, n, s))
    if char == 12:                                   # `0x009d4c`, no mask
        return ('Chameleon/chameleon.%s.anim'
                % ('run' if slot == RUN_SLOT else 'Stand'), None)
    if char == 15:                                   # `0x009bec`, Loki's home
        s = 'Run' if slot == RUN_SLOT else 'stand'
        return ('Loki/Raven.%s.anim' % s, 'Loki/Raven.%s.mask' % s)
    if char in PLAYER_FORM:                          # `0x009dd0`, `0x009ebc`,
        d, f = PLAYER_FORM[char]                     # `0x009b64`
        s = 'Run' if slot == RUN_SLOT else 'stand'
        return ('PerfectOne/%s/%s.%s.anim' % (d, f, s),
                'PerfectOne/%s/%s.%s.mask' % (d, f, s))
    return (None, None)


def loaded_slots(char, nanims):
    """Which slots `LoadCharacterAnims` opens a file for.

    `0x009a78` starts the loop at 1 for every character but Goner, and
    `0x009a94` caps it at 3 for every character past 5 -- nulling the anim and
    mask pointers of slots 3 and up on the way.  So a boss's hit, defend and
    strike animations are not this function's business.
    """
    start = 0 if char == 0 else 1
    end = nanims if char <= 5 else min(3, nanims)
    return range(start, end)


def plut_file(char, slot):
    """`$Characters/<Name>.<slot+1>.plut`, and only Goner has one.

    `0x00a1c4` gates it on `character == 0` and `slot > 0`, and the file's
    first three `PLUT` chunks go to the animation record's `+0x20`, `+0x24`
    and `+0x28` -- three recolours of the generic rithm, picked per mover by
    the byte at its `+0x1e`.
    """
    if char != 0 or slot <= 0:
        return None
    return 'Characters/%s.%d.plut' % (NAMES[0], slot + 1)


# ---------------------------------------------------------------- the assets

def frames(path):
    """Every frame of a mover `.anim` or `.mask` as `(rows, bpp, plut)`.

    One `CCB `/`PLUT` for the whole file and one `PDAT` a frame, which is how
    all of them are laid out except the handful that also carry an `OFST`
    index and an `ANIM` header -- neither of which the frame walk needs.
    """
    d = open(path, 'rb').read()
    ccb = plut = None
    out = []
    for cid, body in cel.chunks(d):
        if cid == b'CCB ' and len(body) >= 72:
            w = struct.unpack_from('>18I', body, 0)
            ccb = dict(flags=w[1], pre0=w[14], pre1=w[15], w=w[16], h=w[17])
        elif cid == b'PLUT':
            n = struct.unpack_from('>I', body, 0)[0]
            plut = list(struct.unpack_from('>%dH' % n, body, 4))
        elif cid == b'PDAT' and ccb:
            rows, bpp = cel.decode_cel(body, ccb['flags'], ccb['pre0'],
                                       ccb['pre1'], ccb['w'], ccb['h'], plut)
            out.append((rows, bpp, plut, bool(ccb['flags'] & 0x20)))
    return out


def mover_art(assets, kinds, slot=RUN_SLOT, views=8):
    """Everything a renderer needs to draw a spawned mover, per character.

    The three sizes are columns of `PerfectMovers.B3D` and are not whole
    units -- Goner's run is 6.196 by 9.674 with its base 2.319 below the
    ground point.  They are quantised to 1/16 of a unit **here**, once, so
    that the scene pack and the Python viewer round them the same way and can
    still be compared pixel for pixel.

    The frames are the first `views` of the animation.  A run is laid out
    `frame = phase * 8 + view`, so those eight are one stride of the gait seen
    from eight sides -- the turntable, without the walk.
    """
    disc = Disc(assets)
    rows = {(r['char'], r['slot']): r
            for r in cast(os.path.join(assets, 'PerfectMovers.B3D'), disc)}
    out = {}
    for k in kinds:
        r = rows.get((k, slot))
        if r is None or not r['animpath']:
            continue
        c = r['cols']
        q = lambda v: round(v / 65536.0 * 16) / 16.0
        out[k] = dict(w=q(c['width']), h=q(c['height']), z=q(c['ground']),
                      frames=frames(r['animpath'])[:views], row=r)
    return out


class Disc(object):
    """Case-insensitive lookup under `Perfect/`, because the code's spelling
    and the disc's differ on a dozen files."""

    def __init__(self, root):
        self.root = root
        self.map = {}
        for base, _, files in os.walk(root):
            for f in files:
                p = os.path.join(base, f)
                rel = os.path.relpath(p, root).replace(os.sep, '/')
                self.map[rel.lower()] = p

    def __call__(self, rel):
        return self.map.get(rel.lower()) if rel else None


# ----------------------------------------------------------------- the cast

def cast(b3d, disc):
    """One row per loaded animation: character, slot, the seven columns from
    `PerfectMovers.B3D` and the files `LoadCharacterAnims` opens for it."""
    out = []
    for char, mv in enumerate(read_any(b3d)['movers']):
        for slot in loaded_slots(char, len(mv['names'])):
            a, m = slot_files(char, slot)
            out.append(dict(char=char, name=NAMES[char], slot=slot,
                            label=mv['names'][slot], anim=a, mask=m,
                            plut=plut_file(char, slot),
                            cols=mv['anims'][slot],
                            animpath=disc(a), maskpath=disc(m)))
    return out


def main():
    import argparse
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--assets', default='extracted/Perfect')
    ap.add_argument('--movers', default=None)
    ap.add_argument('--verify', action='store_true')
    ap.add_argument('--sheet', help='write a contact sheet of the cast')
    a = ap.parse_args()
    b3d = a.movers or os.path.join(a.assets, 'PerfectMovers.B3D')
    disc = Disc(a.assets)
    rows = cast(b3d, disc)

    print('%d animations loaded for %d characters' % (len(rows), len(NAMES)))
    for r in rows:
        c = r['cols']
        n = len(frames(r['animpath'])) if r['animpath'] else 0
        nm = len(frames(r['maskpath'])) if r['maskpath'] else 0
        if r['anim'] is None:
            print('  %-14s slot %d  %-22s   -- the loader stores a null '
                  'pointer here' % (r['name'], r['slot'], r['label']))
            continue
        print('  %-14s slot %d  %-22s %-34s %3d fr  mask %3s  '
              '%6.2f x %-6.2f base %+5.2f'
              % (r['name'], r['slot'], r['label'], r['anim'], n,
                 nm if r['mask'] else '-',
                 c['width'] / 65536.0, c['height'] / 65536.0,
                 c['ground'] / 65536.0))

    if a.sheet:
        write_sheet(rows, a.sheet)

    if a.verify:
        checks = 0
        # 1. every name the rule generates is on the disc
        for r in rows:
            if r['anim'] is None:          # a slot the loader nulls
                continue
            assert r['animpath'], r['anim']
            assert r['mask'] is None or r['maskpath'], r['mask']
            if r['plut']:
                assert disc(r['plut']), r['plut']
            checks += 1
        # 2. a mask matches its anim frame for frame and pixel for pixel --
        #    except on three lieutenants, whose masks are one frame short
        short = 0
        for r in rows:
            if not r['maskpath'] or not r['animpath']:
                continue
            fa, fm = frames(r['animpath']), frames(r['maskpath'])
            if len(fa) != len(fm):
                assert len(fm) == len(fa) - 1, (r['anim'], len(fa), len(fm))
                short += 1
            n = min(len(fa), len(fm))
            for i in range(n):
                assert len(fa[i][0]) == len(fm[i][0]), r['anim']
                assert len(fa[i][0][0]) == len(fm[i][0][0]), r['anim']
            assert fm[0][1] < fa[0][1], (r['mask'], fm[0][1], fa[0][1])
            checks += 1
        assert short == 3, short
        # 3. an overworld animation is a turntable: eight views, so the frame
        #    count divides by eight.  Goner's death and the player forms'
        #    stands are the exceptions, and neither is seen from eight sides.
        turntable = odd = 0
        for r in rows:
            if not r['animpath']:
                continue
            n = len(frames(r['animpath']))
            if n % 8 == 0:
                turntable += 1
            else:
                odd += 1
                assert (r['char'], r['slot']) in ((0, 0), (16, 2), (17, 2),
                                                  (18, 2)), (r['anim'], n)
            checks += 1
        # 4. the rule names every mover asset in `$Characters` but three
        leftover = sorted(v for k, v in disc.map.items()
                          if k.startswith('characters/')
                          and k.endswith(('.anim', '.mask', '.plut'))
                          and k not in {(x or '').lower()
                                        for r in rows
                                        for x in (r['anim'], r['mask'],
                                                  r['plut'])}
                          and 'derez' not in k)
        assert len(leftover) == 3, leftover
        checks += 1
        print('%d checks pass; %d of %d animations are an eight-view '
              'turntable, %d masks are a frame short, and the three files the '
              'rule never names are %s'
              % (checks, turntable, turntable + odd, short,
                 ', '.join(os.path.basename(x) for x in leftover)))


def write_sheet(rows, path):
    """Every character's first standing frame, side by side, scaled to the
    width and height `PerfectMovers.B3D` gives it -- so the sheet is the cast
    at their true relative sizes."""
    # the stand if the character has one, else the run: Goner, Medusa,
    # Riberto and Loki never stand still in the city.
    order = {STAND_SLOT: 2, RUN_SLOT: 1}
    stands = {}
    for r in rows:
        if not r['animpath']:
            continue
        cur = stands.get(r['char'])
        if cur is None or order.get(r['slot'], 0) > order.get(cur['slot'], 0):
            stands[r['char']] = r
    scale = 5.0                                   # pixels per world unit
    cells = []
    for char in sorted(stands):
        r = stands[char]
        f = frames(r['animpath'])[0]
        w = max(1, int(r['cols']['width'] / 65536.0 * scale))
        h = max(1, int(r['cols']['height'] / 65536.0 * scale))
        cells.append((r['name'], f, w, h))
    CW = max(c[2] for c in cells) + 6
    CH = max(c[3] for c in cells) + 6
    W, H = CW * len(cells), CH
    buf = bytearray(b'\x20\x20\x28\xff' * (W * H))
    for i, (nm, f, w, h) in enumerate(cells):
        rows_, bpp, plut, bgnd = f
        sh, sw = len(rows_), len(rows_[0])
        ox, oy = i * CW + 3, CH - 3 - h
        for y in range(h):
            src = rows_[y * sh // h]
            for x in range(w):
                v = src[x * sw // w]
                if v < 0:
                    continue
                if bpp == 16:
                    px = cel.rgb555(v)
                elif plut:
                    px = cel.rgb555(plut[v % len(plut)])
                else:
                    g = (v * 255) // ((1 << bpp) - 1)
                    px = (g, g, g)
                if not (bgnd or any(px)):     # black is clear, as everywhere
                    continue
                o = ((oy + y) * W + ox + x) * 4
                buf[o:o + 4] = bytes(px) + b'\xff'
    raw = b''.join(b'\x00' + bytes(buf[y * W * 4:(y + 1) * W * 4])
                   for y in range(H))
    cel.write_png(path, raw, W, H)
    print('  -> %s, %d characters at %g pixels a world unit'
          % (path, len(cells), scale))


if __name__ == '__main__':
    main()
